#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#)}; t=/${t%%/*}             # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary variables to remove, then release them all.
        shift                   # remove the argument we just consumed
        set -- "$@" "$arg"      # push replacement argument
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     temporary variables that we just consumed; therefore, put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
# arguments to each command line if there are more arguments than MAX_ARGS.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/IPsec_L2TP.c
# shell has://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/IPsec_PPP.c
# neither arrays://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/Protocol.c
# command substitution, so instead we post-process://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
# each://github.com/SoftEtherVPN/SoftEtherVPN/src/Mayaqua/Memory.c
# argument (as a line of input to sed) to://github.com/SoftEtherVPN/SoftEtherVPN/src/bin/hamcore/strindex_cn.h
#://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
# temporary://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
# temp://github.com/SoftEtherVPN/SoftEtherVPN/src/Mayaqua/Network.c
# files://github.com/SoftEtherVPN/SoftEtherVPN/src/Mayaqua/Network.c
#://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
#://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
#://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# temporary://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
# file://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
#://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# with://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# sed://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
#://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
#://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
#://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# arguments to each command line if there are more arguments than MAX_ARGS.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX://github.com/SoftEtherVPN/SoftEtherVPN/softethervpn/blob/master/src/bin/hamcore/strindex_cn.h
# shell has://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# neither arrays://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# nor command substitution, so instead we post-process://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# each://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# argument (as a line of input to sed) to://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# split://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/bin/hamcore/strindex_cn.h
# arguments into separate lines on "whitespace", then using GNU sed (or compatible) to quote each argument
# to allow handling of arguments containing whitespace.
#
# This will break if the sed version available doesn't support the 'e' command or if the
# sed version is too old to understand the '#' comment character.
# This sed expression was tested against GNU sed 4.8 and works.
sed_expr='s/'\''/'\'\\\\\'\''/g;s/.*/'\''&'\''/'

# Use xargs to parse args. Here we do not use a temporary file but instead use a
# "heredoc" to allow for the arguments to contain whitespace.
#
#   * Arguments that contain whitespace will get split across multiple lines
#   * Arguments that contain quotes get mangled
#   * After xargs is done processing, we pass the arguments to java via 'eval'
#
# Note: the trailing whitespace below is intentional.
eval "xargs -a /dev/null -n1 -r sed -e '$sed_expr' <<'EOF' | tr '\n' ' '
$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS
EOF
" 'xargs' java "$@" '